language: node_js
node_js:
  - "stable"

services:
    - mongodb

before_script:
    - mongoimport -d tc-net3-test -c courses --drop --file test/courses.json
    - mongoimport -d tc-net3-test -c subjects --drop --file test/subjects.json
    - mongoimport -d tc-net3-test -c users --drop --file test/users.json
